server:
  port: 8090
  servlet:
    context-path: /app/api
spring:
  config:
    import: security.yaml, database.yaml, mail.yaml
  mail:
    host: "192.168.1.20"
    port: 1025
    templates:
      path: /mail-templates

